// <auto-generated />
using System;
using Aibidia.Homework.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aibidia.Homework.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbMultiTenantContext))]
    [Migration("20250602140211_CreateResumeView")]
    partial class CreateResumeView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Education", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2019, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "NZ University",
                            Qualification = "B.Sc. in Computer Science",
                            ResumeId = 1,
                            StartDate = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Microsoft",
                            Qualification = "AZ-900: Microsoft Azure Fundamentals",
                            ResumeId = 1,
                            StartDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2018, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "Some other University",
                            Qualification = "B.Sc. in Information Technology",
                            ResumeId = 2,
                            StartDate = new DateTime(2014, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experience", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Kainos",
                            Description = "Worked on lots of government projects.",
                            Position = "Software Engineer",
                            ResumeId = 1,
                            StartDate = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Website = "https://kainos.com"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Mr Lender",
                            Description = "Ripped people off with high interest loans.",
                            EndDate = new DateTime(2020, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Position = "Senior Developer",
                            ResumeId = 1,
                            StartDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Website = "https://mrlender.com"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Some Company",
                            Description = "Developed lots of web applications.",
                            EndDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Position = "Frontend Engineer",
                            ResumeId = 2,
                            StartDate = new DateTime(2012, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Website = "https://somecompany.com"
                        });
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Interest", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Muay Thai",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diving",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Traveling",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reading",
                            ResumeId = 2
                        });
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resume", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Looking for remote backend roles.",
                            Email = "owen@gmail.com",
                            FullName = "Owen M",
                            IsActive = true,
                            PhoneNumber = "07123 456 789",
                            Summary = "Full Stack Developer with 5+ years of experience."
                        },
                        new
                        {
                            Id = 2,
                            Description = "Open to contract opportunities.",
                            Email = "jane.doe@example.com",
                            FullName = "Jane Doe",
                            IsActive = true,
                            PhoneNumber = "07234 567 890",
                            Summary = "Frontend Developer with a passion for UI/UX."
                        });
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skill", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = ".NET Core",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vue",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "VB",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = ".NET",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blazor",
                            ResumeId = 2
                        });
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Views.ResumeActive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResumeActive", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Education", b =>
                {
                    b.HasOne("Aibidia.Homework.Domain.Models.Resume", "Resume")
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Experience", b =>
                {
                    b.HasOne("Aibidia.Homework.Domain.Models.Resume", "Resume")
                        .WithMany("Experiences")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Interest", b =>
                {
                    b.HasOne("Aibidia.Homework.Domain.Models.Resume", "Resume")
                        .WithMany("Interests")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Skill", b =>
                {
                    b.HasOne("Aibidia.Homework.Domain.Models.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Aibidia.Homework.Domain.Models.Resume", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Interests");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
